name: 🌠功能请求
description: 提交新功能的建议或想法
labels: ["enhancement / 功能请求"]
title: "[功能请求] "
body:
  - type: textarea
    id: reason
    attributes:
      label: 需求背景
      description: 请详细说明为什么需要这个功能。例如：当前遇到了什么问题？这个功能可以解决什么痛点？
    validations:
      required: false
  - type: textarea
    id: desc
    attributes:
      label: 功能描述
      description: 请具体描述这个功能的核心内容。建议包含：功能的主要目标、预期效果、可能涉及的模块等。
    validations:
      required: false
  - type: textarea
    id: logic
    attributes:
      label: 功能逻辑
      description: 请描述该功能的使用流程和交互逻辑。例如：用户如何触发这个功能？功能的执行步骤是什么？有哪些关键的交互点？
    validations:
      required: true
  - type: textarea
    id: ref
    attributes:
      label: 实现参考
      description: 如果有类似功能的实现案例或参考，请在这里提供。可以包括：其他应用中的类似功能、可能的技术实现方案、相关的文档或资料等。
